site_name: python web开发知识整理
site_author: 'setcreed'
repo_name: 'python-web-dev'
repo_url: 'https://github.com/setcreed/python-web-dev'
theme: readthedocs

copyright: 'Copyright &copy; 2019 - 2020 setcreed'


pages:
    - 课程简介: 'index.md'
    - 第1章 计算机基础:
        - 01_markdown文档的编写: '第1章_计算机基础/01_markdown文档的编写.md'
        - 02_计算机基础: '第1章_计算机基础/02_计算机基础.md'
    - 第2章 python解释器和集成环境:
        - 01_python介绍: '第2章_python解释器和集成环境/01_python介绍.md'
        - 02_python解释器pip源修改: '第2章_python解释器和集成环境/02_python解释器pip源修改.md'
        - 03_pycharm介绍: '第2章_python解释器和集成环境/03_pycharm介绍.md'
    - 第3章 python基础:
        - 01_变量与常量: '第3章_python基础/01_变量与常量.md'
        - 02_注释: '第3章_python基础/02_注释.md'
        - 03_python内存管理: '第3章_python基础/03_python内存管理.md'
        - 04_基本数据类型: '第3章_python基础/04_基本数据类型.md'
        - 05_花式赋值，解压缩、用户交互，格式化输出: '第3章_python基础/05_花式赋值，解压缩、用户交互，格式化输出.md'
        - 06_数字类型常用方法: '第3章_python基础/06_数字类型常用方法.md'
        - 07_字符串类型常用方法: '第3章_python基础/07_字符串类型常用方法.md'
        - 08_列表常用方法: '第3章_python基础/08_列表常用方法.md'
        - 09_元组常用方法: '第3章_python基础/09_元组常用方法.md'
        - 10_字典常用方法: '第3章_python基础/10_字典常用方法.md'
        - 11_集合常用方法: '第3章_python基础/11_集合常用方法.md'
        - 12_深浅拷贝: '第3章_python基础/12_深浅拷贝.md'
        - 13_异常处理: '第3章_python基础/13_异常处理.md'
        - 14_基本运算符: '第3章_python基础/14_基本运算符.md'
        - 15_流程控制: '第3章_python基础/15_流程控制.md'
    - 第4章 文件处理:
        - 01_字符编码: '第4章_文件处理/01_字符编码.md'
        - 02_python2与python3字符编码的区别: '第4章_文件处理/02_python2与python3字符编码的区别.md'
        - 03_文件操作: '第4章_文件处理/03_文件操作.md'
    - 第5章 函数基础:
        - 01_函数的定义: '第5章_函数基础/01_函数的定义.md'
        - 02_函数的调用、函数的返回值: '第5章_函数基础/02_函数的调用、函数的返回值.md'
        - 03_函数的参数: '第5章_函数基础/03_函数的参数.md'
        - 04_函数的对象、函数的嵌套: '第5章_函数基础/04_函数的对象、函数的嵌套.md'
        - 05_名称空间与作用域: '第5章_函数基础/05_名称空间与作用域.md'
    - 第6章 函数进阶操作:
        - 01_闭包函数: '第6章_函数进阶操作/01_闭包函数.md'
        - 02_装饰器: '第6章_函数进阶操作/02_装饰器.md'
        - 03_迭代器: '第6章_函数进阶操作/03_迭代器.md'
        - 04_三元表达式: '第6章_函数进阶操作/04_三元表达式.md'
        - 05_列表推导式、字典生成式、生成器: '第6章_函数进阶操作/05_列表推导式、字典生成式、生成器.md'
        - 06_函数递归: '第6章_函数进阶操作/06_函数递归.md'
        - 07_匿名函数: '第6章_函数进阶操作/07_匿名函数.md'
        - 08_内置函数: '第6章_函数进阶操作/08_内置函数.md'
    - 第7章 模块基础:
        - 01_python模块介绍: '第7章_模块基础/01_python模块介绍.md'
        - 02_循环导入问题: '第7章_模块基础/02_循环导入问题.md'
        - 03_python的包: '第7章_模块基础/03_python的包.md'
    - 第8章 python常用模块:
        - 01_os模块: '第8章_python常用模块/01_os模块.md'
        - 02_sys模块: '第8章_python常用模块/02_sys模块.md'
        - 03_json和pickle模块: '第8章_python常用模块/03_json和pickle模块.md'
        - 04_logging模块: '第8章_python常用模块/04_logging模块.md'
        - 05_time模块: '第8章_python常用模块/05_time模块.md'
        - 06_datetime模块: '第8章_python常用模块/06_datetime模块.md'
        - 07_random模块: '第8章_python常用模块/07_random模块.md'
        - 08_typing模块: '第8章_python常用模块/08_typing模块.md'
        - 09_hashlib和hmac模块: '第8章_python常用模块/09_hashlib和hmac模块.md'
        - 10_re模块: '第8章_python常用模块/10_re模块.md'
        - 11_数据分析常用的三个模块: '第8章_python常用模块/11_数据分析常用的三个模块.md'
        - 12_jiieba库、wordcloud词云: '第8章_python常用模块/12_jiieba库、wordcloud词云.md'
        - 13_exec模块: '第8章_python常用模块/13_exec模块.md'
        - 14 subprocess模块: '第8章_python常用模块/14 subprocess模块.md'
    - 第9章_面向对象基础:
        - 01_面向对象编程介绍: '第9章_面向对象基础/01_面向对象编程介绍.md'
        - 02_类和对象: '第9章_面向对象基础/02_类和对象.md'
        - 03_对象和类的查找顺序: '第9章_面向对象基础/03_对象和类的查找顺序.md'
        - 04_对象的绑定方法: '第9章_面向对象基础/04_对象的绑定方法.md'
    - 第10章_面向对象进阶:
        - 01_类的继承: '第10章_面向对象进阶/01_类的继承.md'
        - 02_类的派生: '第10章_面向对象进阶/02_类的派生.md'
        - 03_菱形继承问题: '第10章_面向对象进阶/03_菱形继承问题.md'
        - 04_类的组合: '第10章_面向对象进阶/04_类的组合.md'
        - 05_类的封装: '第10章_面向对象进阶/05_类的封装.md'
        - 06_property: '第10章_面向对象进阶/06_property.md'
        - 07_类的多态: '第10章_面向对象进阶/07_类的多态.md'
        - 08_类的绑定方法和非绑定方法: '第10章_面向对象进阶/08_类的绑定方法和非绑定方法.md'
        - 09_isinstance和issubclass: '第10章_面向对象进阶/09_isinstance和issubclass.md'
    - 第11章_面向对象高级特性:
        - 01_反射: '第11章_面向对象高级特性/01_反射.md'
        - 02_类的魔法方法: '第11章_面向对象高级特性/02_类的魔法方法.md'
        - 03_元类: '第11章_面向对象高级特性/03_元类.md'
        - 04_单例模式: '第11章_面向对象高级特性/04_单例模式.md'
    - 第12章_网络编程:
        - 01_软件开发架构: '第12章_网络编程/01_软件开发架构.md'
        - 02_OSI七层模型: '第12章_网络编程/02_OSI七层模型.md'
        - 03_TCP三次握手，四次挥手: '第12章_网络编程/03_TCP三次握手，四次挥手.md'
        - 04_基于TCP协议的socket套接字编程: '第12章_网络编程/04_基于TCP协议的socket套接字编程.md'
        - 05_TCP粘包问题、解决粘包问题: '第12章_网络编程/05_TCP粘包问题、解决粘包问题.md'
        - 06_基于UDP协议的socket套接字编程: '第12章_网络编程/06_基于UDP协议的socket套接字编程.md'
        - 07_socketserver: '第12章_网络编程/07_socketserver.md'
        - 08_网络编程小结: '第12章_网络编程/08_网络编程小结.md'
    - 第13章_并发编程:
        - 01_操作系统发展史: '第13章_并发编程/01_操作系统发展史.md'
        - 02_进程基础: '第13章_并发编程/02_进程基础.md'
        - 03_同步异步阻塞非阻塞: '第13章_并发编程/03_同步异步阻塞非阻塞.md'
        - 04_进程特性: '第13章_并发编程/04_进程特性.md'
        - 05_TCP协议套接字，服务端实现接收客户端的连接并发: '第13章_并发编程/05_TCP协议套接字，服务端实现接收客户端的连接并发.md'
        - 06_进程互斥锁: '第13章_并发编程/06_进程互斥锁.md'
        - 07_进程队列: '第13章_并发编程/07_进程队列.md'
        - 08_进程间通信: '第13章_并发编程/08_进程间通信.md'
        - 09_生产者与消费者: '第13章_并发编程/09_生产者与消费者.md'
        - 10_线程: '第13章_并发编程/10_线程.md'
        - 11_GIL全局解释器锁: '第13章_并发编程/11_GIL全局解释器锁.md'
        - 12_多线程应用: '第13章_并发编程/12_多线程应用.md'
        - 13_死锁和递归锁: '第13章_并发编程/13_死锁和递归锁.md'
        - 14_信号量、线程队列: '第13章_并发编程/14_信号量、线程队列.md'
        - 15_Event事件: '第13章_并发编程/15_Event事件.md'
        - 16_进程池与线程池: '第13章_并发编程/16_进程池与线程池.md'
        - 17_协程: '第13章_并发编程/17_协程.md'
        - 18_Gevent模块: '第13章_并发编程/18_Gevent模块.md'
        - 19_TCP服务端socket套接字实现协程: '第13章_并发编程/19_TCP服务端socket套接字实现协程.md'
        - 20_并发编程小结: '第13章_并发编程/20_并发编程小结.md'
    - 第14章_常用数据库:
        - MySQL数据库:
            - 00_MySQL初始: '第14章_常用数据库/MySQL数据库/00_MySQL初始.md'
            - 01_MySQL字符集: '第14章_常用数据库/MySQL数据库/01_MySQL字符集.md'
            - 02_MySQL对数据库、表的操作: '第14章_常用数据库/MySQL数据库/02_MySQL对数据库、表的操作.md'
            - 03_MySQL操作数据行: '第14章_常用数据库/MySQL数据库/03_MySQL操作数据行.md'
            - 04_单表查询: '第14章_常用数据库/MySQL数据库/04_单表查询.md'
            - 05_多表查询: '第14章_常用数据库/MySQL数据库/05_多表查询.md'
            - 06_python操作MySQL: '第14章_常用数据库/MySQL数据库/06_python操作MySQL.md'
            - 07_MySQL索引: '第14章_常用数据库/MySQL数据库/07_MySQL索引.md'
            - 08_explain查询性能分析: '第14章_常用数据库/MySQL数据库/08_explain查询性能分析.md'
            - 09_慢查询日志: '第14章_常用数据库/MySQL数据库/09_慢查询日志.md'
            - 10_MySQL高级特性: '第14章_常用数据库/MySQL数据库/10_MySQL高级特性.md'
            - 11_数据库备份: '第14章_常用数据库/MySQL数据库/11_数据库备份.md'
            - 12_数据库表设计: '第14章_常用数据库/MySQL数据库/12_数据库表设计.md'
        - PostgreSQL数据库:
            - postgresql安装及简单使用: '第14章_常用数据库/PostgreSQL数据库/postgresql安装及简单使用.md'
        - Redis数据库:
            - 01_Redis简介及安装: '第14章_常用数据库/Redis数据库/01_Redis简介及安装.md'
            - 02_redis数据类型操作: '第14章_常用数据库/Redis数据库/02_redis数据类型操作.md'
            - 03_redis系统级命令: '第14章_常用数据库/Redis数据库/03_redis系统级命令.md'
            - 04_redis杂谈: '第14章_常用数据库/Redis数据库/04_redis杂谈.md'
            - 05_Redis操作以及python操作redis: '第14章_常用数据库/Redis数据库/05_Redis操作以及python操作redis.md'
            - 06_redis系列总结: '第14章_常用数据库/Redis数据库/06_redis系列总结.md'
            - 07_redis面试题: '第14章_常用数据库/Redis数据库/07_redis面试题.md'
    - 第15章_前端:
        - 01_前端之html基础: '第15章_前端/01_前端之html基础.md'
        - 02_html之form表单: '第15章_前端/02_html之form表单.md'
        - 03_前端之css(一): '第15章_前端/03_前端之css(一).md'
        - 04_前端之css(二): '第15章_前端/04_前端之css(二).md'
        - 05_前端之js: '第15章_前端/05_前端之js.md'
        - 06_前端基础之BOM和DOM: '第15章_前端/06_前端基础之BOM和DOM.md'
        - 07_jQuery: '第15章_前端/07_jQuery.md'
        - 08_前端之Bootstrap基础: '第15章_前端/08_前端之Bootstrap基础.md'